service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=2.24.0"

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Comment if you don't have a DynamoDB running locally
    #  noStart: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: todos/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: todos/list.list
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: todos/get.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
  update:
    handler: todos/update.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  createQuote:
      handler: quotes/createQuote.createQuote
      events:
        - http:
            path: quote
            method: post
            cors: true
  generateQuote:
      handler: quotes/generateQuote.generateQuote
      events:
        - http:
            path: random
            method: post
            cors: true
  listQuotes:
    handler: quotes/listQuotes.listQuotes
    events:
      - http:
          path: quotes
          method: get
          cors: true
  getQuote:
    handler: quotes/getQuote.getQuote
    events:
      - http:
          path: quote/{id}
          method: get
          cors: true
  updateQuote:
    handler: quotes/updateQuote.updateQuote
    events:
      - http:
          path: quote/{id}
          method: put
          cors: true
  deleteQuote:
    handler: quotes/deleteQuote.deleteQuote
    events:
      - http:
          path: quote/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
