service: serverless-rest-api-with-dynamodb

frameworkVersion: ">=2.24.0"

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Comment if you don't have a DynamoDB running locally
    #  noStart: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'dev'
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: api/create.create
    description: Create language information.
    events:
      - http:
          path: languages
          method: post
          cors: true

  list:
    handler: api/list.list
    description: List all languages.
    events:
      - http:
          path: languages
          method: get
          cors: true

  get:
    handler: api/get.get
    description: Retrieve an existing language. You need to supply the unique ID for the language.
    events:
      - http:
          path: languages/{id}
          method: get
          cors: true

  update:
    handler: api/update.update
    description: Update a specific language with the attributes that you pass in.
    events:
      - http:
          path: languages/{id}
          method: put
          cors: true

  remove:
    handler: api/remove.remove
    description: Remove a language item with the partition key id.
    events:
      - http:
          path: languages/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
